/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface AuthSession {
  expires_at: string;
  id: string;
  user_did: string;
}

export interface BskyAuthSessions {
  created_at: Generated<string>;
  key: string;
  session: string;
}

export interface BskyAuthState {
  key: string | null;
  state: string;
}

export interface DB {
  auth_session: AuthSession;
  bsky_auth_sessions: BskyAuthSessions;
  bsky_auth_state: BskyAuthState;
}
